#define WIFI_SSID "CMU-DEVICE"
#define WIFI_PASS ""
#define SENSOR_ID "b78a4d8e-54cb-42f0-9dcb-b223663dfce5"
#define SENSOR_TYPE "grid_eye"
#define SERVER_URL "http://kinect.andrew.cmu.edu:8000/hs/events"
#define SERVER_AUTH "Basic aHNfdXNlcjpycGNzX2hzMjAxOQ=="
