#define WIFI_SSID "CMU-DEVICE"
#define WIFI_PASS ""
#define SENSOR_ID "505d642b-730f-41ad-a5ee-2dfc04a71b71"
#define SENSOR_TYPE "door"
#define SERVER_URL "http://kinect.andrew.cmu.edu:8000/hs/events"
#define SERVER_AUTH "Basic aHNfdXNlcjpycGNzX2hzMjAxOQ=="
